Tactile pcl threshold
ubi-agni/tactile_toolbox pull request #6
Opened 2020-10-02 18:19 UTC by guihomework

To avoid useless data being produced like empty data or PCLs stemming from contact noise, this PR adds the possibility to define a threshold under which the contact_state value is not considered for PCL generation

2020-10-03 15:44 UTC, rhaschke requested changes
Please address some nitpicks before merging.

2020-10-03 15:44 UTC, rhaschke commented on tactile_pcl/src/pcl_collector.cpp
> +PCLCollector::PCLCollector(const std::string &target_frame, const float &threshold)
The data type should be double as [`geometry_msgs::Vector3`](http://docs.ros.org/melodic/api/geometry_msgs/html/msg/Vector3.html) uses double as well.
References (or pointers) are only sensible for complex data types (class or struct instances). Basic data types (int, float, etc) should be passed as is.
Internally (under the hood) a reference is a pointer that needs to be dereferenced, which adds extra cost for basic types, but avoids (more costly) data copying for complex data types. For basic types, copying the data and copying the pointer is about the same effort.
```suggestion
PCLCollector::PCLCollector(const std::string &target_frame, const double threshold)
```

2020-10-03 15:44 UTC, rhaschke commented on tactile_pcl/src/pcl_collector.h
> +	PCLCollector(const std::string &target_frame="", const float &threshold=0.0);
```suggestion
	PCLCollector(const std::string &target_frame="", const double threshold=0.0);
```

2020-10-03 15:44 UTC, rhaschke commented on tactile_pcl/src/pcl_collector.h
> +	float threshold_;
```suggestion
	double threshold_;
```

2020-10-03 15:44 UTC, rhaschke commented on tactile_pcl/src/tactile_pcl_node.cpp
> +	PCLCollector collector(nh_priv.param<std::string>("frame", ""), threshold);
```suggestion
	PCLCollector collector(nh_priv.param<std::string>("frame", ""), nh_priv.param<double>("threshold", 0.0));
```

2020-10-03 17:09 UTC, guihomework commented on tactile_pcl/src/tactile_pcl_node.cpp
> +	PCLCollector collector(nh_priv.param<std::string>("frame", ""), threshold);
all done with your authorship

2020-10-04 09:00 UTC, rhaschke approved these changes

2020-10-04 09:22 UTC, merged